version: 0.0
os: linux
files:
  # Source code
  - source: build/libs/spring-boot-reference-app-1.0.jar
    destination: /usr/local/bin/spring-boot-reference-app
  # Systemd service
  - source: deploy/aws/codedeploy/files/etc/systemd/system/spring-boot-reference-app.service
    destination: /etc/systemd/system
  # Nginx configuration
  - source: deploy/aws/codedeploy/files/etc/nginx/spring-boot-reference-app.conf
    destination: /etc/nginx
hooks:
  # Called to stop application service.
  ApplicationStop:
    - location: deploy/aws/codedeploy/hooks/ApplicationStop/stop_service
      timeout: 600
      runas: root
  # Called before copying files from 'files' section.
  BeforeInstall:
    - location: deploy/aws/codedeploy/hooks/BeforeInstall/install_system_packages
      timeout: 600
      runas: root
  # Called after all files are copied.
  AfterInstall:
    - location: deploy/aws/codedeploy/hooks/AfterInstall/symlink_nginx_conf
      timeout: 600
      runas: root
  # Called to start application service.
  ApplicationStart:
    - location: deploy/aws/codedeploy/hooks/ApplicationStart/start_service
      timeout: 600
      runas: root
